
version: '3.1'
services:
  teamspeak:
    image: teamspeak
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: ${TSDB_USERNAME}
      TS3SERVER_DB_PASSWORD: ${TSDB_PASS}
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    networks:
      - tipi_main_network
    depends_on:
      - db
    labels:
      # Main
      traefik.enable: true
      traefik.http.services.teamspeak.loadbalancer.server.port: 9987
      traefik.http.routers.teamspeak-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.teamspeak-insecure.entrypoints: web
      traefik.http.routers.teamspeak-insecure.service: teamspeak
      #
      runtipi.managed: true 
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${TSDB_PASS}
      MYSQL_DATABASE: teamspeak
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true