
version: '3.1'
services:
  teamspeak:
    image: teamspeak
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: ${TSDB_USERNAME}
      TS3SERVER_DB_PASSWORD: ${TSDB_PASS}
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    networks:
      - tipi_main_network
    depends_on:
      - db
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.esphome-web-redirect.redirectscheme.scheme: https
      traefik.http.services.esphome.loadbalancer.server.port: 9987
      # Web
      traefik.http.routers.teamspeak-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.teamspeak-insecure.entrypoints: web
      traefik.http.routers.teamspeak-insecure.service: teamspeak
      traefik.http.routers.teamspeak-insecure.middlewares: teamspeak-web-redirect
      # Websecure
      traefik.http.routers.teamspeak.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.teamspeak.entrypoints: websecure
      traefik.http.routers.teamspeak.service: teamspeak
      traefik.http.routers.teamspeak.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.teamspeak-local-insecure.rule: Host(`teamspeak.${LOCAL_DOMAIN}`)
      traefik.http.routers.teamspeak-local-insecure.entrypoints: web
      traefik.http.routers.teamspeak-local-insecure.service: teamspeak
      traefik.http.routers.teamspeak-local-insecure.middlewares: teamspeak-web-redirect
      # Local domain secure
      traefik.http.routers.teamspeak-local.rule: Host(`teamspeak.${LOCAL_DOMAIN}`)
      traefik.http.routers.teamspeak-local.entrypoints: websecure
      traefik.http.routers.teamspeak-local.service: teamspeak
      traefik.http.routers.teamspeak-local.tls: true
      #
      runtipi.managed: true 
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${TSDB_PASS}
      MYSQL_DATABASE: teamspeak
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true